### PR TITLE
PHP content and classes

### PR DESCRIPTION
**Pull request by mesour**

### CODE REVIEW

**Comment by bvelastegui** [comment]
Great job, congratulations!

Do you plan to add support for `@formatter:off/on` annotation?

**Comment by dakorpar** [comment]
Who's owner of this organization? Is anybody here even active to be able to merge this?

**Comment by mesour** [comment]
@matej21 or @JanTvrdik can merge it. But I found a bug in showing help and description if use completion for Latte filters. I want to fix it and after this, it will be able to merge.

**Comment by JanTvrdik** [comment]
@mesour You should have maintainer access on this repository. Feel free to merge this when you think it's ready.

**Pull request merged**
